_security_logout:
    resource: security.route_loader.logout
    type: service

App\EventListener\RuntimeConstraintExceptionListener:
    tags:
        - { name: kernel.event_listener, event: kernel.exception }

App\Service\RequestCheckerService:
    autowire: true
    autoconfigure: true
